### ISSUE TITLE
请问是哪个版本的yolov5以及yolov5的ONNX是如何生成的

### ISSUE THREAD

**Issue by wuqingzhou828** [triple-Mu/YOLO-TensorRT8#2]

**Comment by wuqingzhou828** [comment]
> 

导出：python export.py --dynamic --simplify --inplace

**Comment by triple-Mu** [comment]
> 

可以用网盘发一分本项目生成的onnx我看看

**Comment by wuqingzhou828** [comment]
> > 
> 
> 可以用网盘发一分本项目生成的onnx我看看

我用了最新版本去 python export.py --weights yolov5s.pt --include onnx 得到固定的onnx
然后 run test
得到结果如下：
Finish warmup 10 times
Infer image finish use 0.0036620981991291046 s
result: []
