### ISSUE TITLE
Are you planning to support YOLOX

### ISSUE THREAD

**Issue by taka-wang** [triple-Mu/YOLO-TensorRT8#6]
Hi, there!

Thank you for your fantastic repo,  I saw an empty yolox folder in your repo.
Are you planning to support YOLOX?

Thanks a lot.

**Comment by triple-Mu** [comment]
Sure!
Even better if you can pr！

**Comment by triple-Mu** [comment]
> Sure!
> Even better if you can pr！

Sure!
Even better if you can pr！

**Comment by triple-Mu** [comment]
> Hi, there!
> 
> Thank you for your fantastic repo, I saw an empty yolox folder in your repo. Are you planning to support YOLOX?
> 
> Thanks a lot.

Sure!
Even better if you can pr！
